Solution added
gkhrshch/internetshop pull request #10
Opened 2019-10-06 07:23 UTC by gkhrshch

2019-10-06 07:43 UTC, boroda4436 requested changes

2019-10-06 07:43 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/RoleDao.java
> +    void addRole(User user);
@gkhrshch Я б перемісти цей метод в UserDao

2019-10-06 07:43 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +                user.setName(resultSet.getString("name"));
@gkhrshch Is it possible to move this duplicated code to a separate method?
```suggestion
                private User getUserFromResultSet(ResultSet resultSet) {
                User user = new User();
                ...
                user.setName(resultSet.getString("name"));
                ....
```

2019-10-06 11:02 UTC, boroda4436 requested changes

2019-10-06 11:02 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +    public void addRole(User user) {
```suggestion
    public void addRole(User user, Role role) {
```
@gkhrshch Якщо ти додаєш роль - то краще явно вказати яку роль ти додаєш

2019-10-06 11:02 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +        String role = user.getRoles().stream().findFirst().get().getRoleName().toString();
@gkhrshch тоді цей стрім прибираєш взагалі

2019-10-06 11:02 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +        String role = user.getRoles().stream().findFirst().get().getRoleName().toString();
Це ж вщааглі не валідна поведінка. Чому тільки першу роль ти будеш витягувати? А якщо ти хочеш додати одразу 3-4 ролі. Як відпрацює метод findFirst() в цьому випадку?

2019-10-06 11:02 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +            getRoleIdStmt.setString(1, role);
@gkhrshch А ти тестував своє рішення? role_id в таблиці в тебе повинно бути INT or BIGINT. А в тебе в прикладі role - це String. Якщо ти пишеш такий код - у мене одразу підозра: а) чи ти розумієш що відбувається в твоєму коді, б) чи ти взагалі перевіряєш свій код

2019-10-06 11:37 UTC, gkhrshch commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +            getRoleIdStmt.setString(1, role);
@boroda4436 там String role - то role_name, а не role_id, которий інт.
Але да, там щось не те із новими юзерами, я просто тестив весь функціонал раніше створеним юзером, і це не попало до моєї уваги. Зараз переписувати буду.

2019-10-06 15:43 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +            getRoleIdStmt.setString(1, role);
@gkhrshch Завтра давай розберемо на уроці зранку

2019-10-06 18:39 UTC, boroda4436 requested changes

2019-10-06 18:39 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/web/filters/AuthorizationFilter.java
> +                    logger.info("Role: " + roleDao.getRoles(user.get()).toString());
тут можна було залишити як було і ініціалізувати ролі користувача в методі userDao.get(userId)

2019-10-06 18:39 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +                getRoleIdStmt.setString(1, String.valueOf(role.getRoleName()));
@gkhrshch Сорі, я не побачив першу getRoleIdQuery. Це рішення ок, буде працювати. Але все одно, метод повинен приймати ролі на вхід, так буле більш корректно _addRoles(User user, Set<Role> roles)_

2019-10-07 06:33 UTC, boroda4436 approved these changes

2019-10-07 06:56 UTC, merged